#!/bin/sh

. /Applications/mampstack-7.3.16-2/scripts/setenv.sh

exec /Applications/mampstack-7.3.16-2/php/sbin/.php-fpm.bin -y /Applications/mampstack-7.3.16-2/php/etc/php-fpm.conf -p /Applications/mampstack-7.3.16-2/php/var/ -c /Applications/mampstack-7.3.16-2/php/etc/php.ini "$@"
